import type { Vendor } from "./catalog.ts";
// Free tiers, priority 0–19 = latency order (used by `fast`); `auto` ranks by QUALITY instead.
export const FREE: Vendor[] = [
  { vendor: "groq", tps: 400, maxOut: 5500, maxIn: 6500, base: "https://api.groq.com/openai/v1", keyEnv: "GROQ_API_KEY", priority: 0, tags: ["fast"],
    models: ["qwen/qwen3.8-27b", "openai/gpt-oss-120b", "openai/gpt-oss-20b"], prefer: "gpt-oss|qwen|llama" },
  { vendor: "cerebras", tps: 1200, maxOut: 8000, base: "https://api.cerebras.ai/v1", keyEnv: "CEREBRAS_API_KEY", priority: 1, tags: ["fast"],
    models: ["qwen-3.8-27b", "gpt-oss-120b", "gemma-4-31b"], prefer: "gpt-oss|qwen|llama" },
  { vendor: "sambanova", tps: 300, base: "https://api.sambanova.ai/v1", keyEnv: "SAMBANOVA_API_KEY", priority: 2, tags: ["fast", "reasoning"],
    models: ["MiniMax-M3", "DeepSeek-V3.2", "gpt-oss-120b", "Meta-Llama-3.3-70B-Instruct"], prefer: "minimax|deepseek|gpt-oss|llama" },
  { vendor: "openrouter", tps: 30, ttft: 4000, base: "https://openrouter.ai/api/v1", keyEnv: "OPENROUTER_API_KEY", priority: 3, tags: ["coder", "reasoning", "long"],
    // ordered by throughput on the free tier: the 550B ultra model times out inside a 50 s turn and is a last resort
    models: ["nvidia/nemotron-3-super-120b-a12b:free", "google/gemma-4-31b-it:free", "nvidia/nemotron-3.5-lightning:free", "thinkingmachines/inkling:free", "nvidia/nemotron-3-ultra-550b-a55b:free"],
    prefer: "super|gemma|lightning" },
  { vendor: "huggingface", tps: 50, base: "https://router.huggingface.co/v1", keyEnv: "HF_TOKEN", priority: 4, tags: ["coder", "reasoning", "long"],
    models: ["deepseek-ai/DeepSeek-V4-Pro", "moonshotai/Kimi-K3", "zai-org/GLM-5.3", "deepseek-ai/DeepSeek-V4-Flash", "Qwen/Qwen3-Coder-Next", "Qwen/Qwen3.8-27B", "openai/gpt-oss-120b", "zai-org/GLM-5.3-Flash"], prefer: "deepseek|kimi|glm|qwen|gpt-oss" },
  { vendor: "gemini", tps: 150, base: "https://generativelanguage.googleapis.com/v1beta/openai", keyEnv: "GEMINI_API_KEY", priority: 5, tags: ["fast", "long", "vision"],
    models: ["gemini-2.5-flash-lite", "gemini-2.5-flash", "gemini-2.0-flash"], prefer: "flash" },
  { vendor: "mistral", tps: 80, base: "https://api.mistral.ai/v1", keyEnv: "MISTRAL_API_KEY", priority: 6, tags: ["coder"],
    models: ["mistral-small-latest", "ministral-14b-latest", "ministral-8b-latest", "devstral-small-latest"], prefer: "mistral-small|ministral" },
  { vendor: "nvidia_nim", tps: 40, base: "https://integrate.api.nvidia.com/v1", keyEnv: "NVIDIA_API_KEY", priority: 20, tags: ["reasoning"],
    models: ["nvidia/llama-3.1-nemotron-51b-instruct", "mistralai/mistral-nemotron", "meta/llama-3.2-90b-vision-instruct"], prefer: "nemotron-(51|70)b|mistral-nemotron" },
  { vendor: "zai", base: "https://open.bigmodel.cn/api/paas/v4", keyEnv: "ZAI_API_KEY", priority: 8, tags: ["coder"],
    models: ["glm-5.3-flash", "glm-4.5-air", "glm-5-turbo"], prefer: "flash|air" },
  { vendor: "cohere", base: "https://api.cohere.ai/compatibility/v1", keyEnv: "COHERE_API_KEY", priority: 9,
    models: ["command-a-03-2025", "command-r7b-12-2024", "command-r-plus"], prefer: "command" },
  { vendor: "cloudflare", tps: 100, base: "https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT_ID}/ai/v1", keyEnv: "CLOUDFLARE_API_KEY", priority: 10, tags: ["fast"],
    models: ["@cf/openai/gpt-oss-120b", "@cf/meta/llama-3.3-70b-instruct-fp8-fast", "@cf/qwen/qwen3-30b-a3b-fp8"], prefer: "gpt-oss|llama-3.3|qwen" },
  // DEEPINFRA and FIREWORKS: both keys have been set on this val since April and neither vendor existed
  // in the catalog, so two funded providers sat unused while every wired instance was out of credit.
  { vendor: "deepinfra", tps: 90, base: "https://api.deepinfra.com/v1/openai", keyEnv: "DEEPINFRA_API_KEY", priority: 7, tags: ["coder", "reasoning"],
    models: ["openai/gpt-oss-120b", "Qwen/Qwen3-Coder-480B-A35B-Instruct", "meta-llama/Llama-3.3-70B-Instruct"], prefer: "gpt-oss|qwen3-coder|llama-3.3" },
  { vendor: "fireworks", tps: 120, base: "https://api.fireworks.ai/inference/v1", keyEnv: "FIREWORKS_API_KEY", priority: 7, tags: ["coder", "fast"],
    models: ["accounts/fireworks/models/gpt-oss-120b", "accounts/fireworks/models/qwen3-coder-480b-a35b-instruct", "accounts/fireworks/models/llama-v3p3-70b-instruct"], prefer: "gpt-oss|qwen3-coder|llama" },
  { vendor: "together", tps: 80, base: "https://api.together.xyz/v1", keyEnv: "TOGETHER_API_KEY", priority: 11,
    models: ["openai/gpt-oss-20b", "Qwen/Qwen3-14B", "meta-llama/Llama-3.3-70B-Instruct", "openai/gpt-oss-120b"], prefer: "gpt-oss-20b|qwen3-14b|llama-3.3-70b-instruct$" },
  { vendor: "siliconflow", base: "https://api.siliconflow.cn/v1", keyEnv: "SILICONFLOW_API_KEY", priority: 12,
    models: ["Qwen/Qwen3-8B", "THUDM/GLM-4-9B-0414"], prefer: "qwen3-8b|glm" },
  { vendor: "ovh", base: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1", keyEnv: "OVH_AI_ENDPOINTS_ACCESS_TOKEN", priority: 13,
    models: ["Meta-Llama-3_3-70B-Instruct", "gpt-oss-120b", "Qwen3-32B"], prefer: "llama|gpt-oss|qwen" },
  { vendor: "chutes", base: "https://llm.chutes.ai/v1", keyEnv: "CHUTES_API_KEY", priority: 14,
    models: ["openai/gpt-oss-120b", "Qwen/Qwen3-235B-A22B-Instruct-2507"], prefer: "gpt-oss|qwen" },
  { vendor: "novita", base: "https://api.novita.ai/v3/openai", keyEnv: "NOVITA_API_KEY", priority: 15,
    models: ["openai/gpt-oss-120b", "meta-llama/llama-3.3-70b-instruct"], prefer: "gpt-oss|llama-3.3" },
  { vendor: "hyperbolic", base: "https://api.hyperbolic.xyz/v1", keyEnv: "HYPERBOLIC_API_KEY", priority: 16,
    models: ["openai/gpt-oss-120b", "meta-llama/Llama-3.3-70B-Instruct"], prefer: "gpt-oss|llama-3.3" },
  { vendor: "dashscope", base: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1", keyEnv: "DASHSCOPE_API_KEY", priority: 17, tags: ["coder"],
    models: ["qwen-plus", "qwen3-coder-plus", "qwen-turbo"], prefer: "qwen" },
  { vendor: "scaleway", base: "https://api.scaleway.ai/v1", keyEnv: "SCW_SECRET_KEY", priority: 18,
    models: ["gpt-oss-120b", "llama-3.3-70b-instruct"], prefer: "gpt-oss|llama" },
  { vendor: "featherless", base: "https://api.featherless.ai/v1", keyEnv: "FEATHERLESS_API_KEY", priority: 19,
    models: ["meta-llama/Llama-3.3-70B-Instruct"], prefer: "llama-3.3|qwen" },
];
